# Author: Matthew Jackson
# collects the authors and the dates when they touched each file
# in the list of files generated by the adapted file CollectFiles.py
import json
import requests
import csv
import os

print("starting...")
if not os.path.exists("data"):
    os.makedirs("data")


# GitHub Authentication function
def github_auth(url, lsttoken, ct):
    jsonData = None
    try:
        ct = ct % len(lstTokens)
        headers = {"Authorization": "Bearer {}".format(lsttoken[ct])}
        request = requests.get(url, headers=headers)
        jsonData = json.loads(request.content)
        ct += 1
    except Exception as e:
        pass
        print(e)
    return jsonData, ct


# @repo, GitHub repo
def countfiles(dictfiles, lsttokens, repo, source_ext):
    ipage = 1  # url page counter
    ct = 0  # token counter

    try:
        # loop though all the commit pages until the last returned empty page
        while True:
            spage = str(ipage)
            commitsUrl = (
                "https://api.github.com/repos/"
                + repo
                + "/commits?page="
                + spage
                + "&per_page=100"
            )
            jsonCommits, ct = github_auth(commitsUrl, lsttokens, ct)
            # break out of the while loop if there are no more commits in the pages
            if len(jsonCommits) == 0:
                break
            # iterate through the list of commits in spage
            for shaObject in jsonCommits:
                sha = shaObject["sha"]
                author = shaObject["commit"]["author"]["name"]
                date = shaObject["commit"]["author"]["date"]
                # For each commit, use the GitHub commit API to extract the files touched by the commit
                shaUrl = "https://api.github.com/repos/" + repo + "/commits/" + sha
                shaDetails, ct = github_auth(shaUrl, lsttokens, ct)
                filesjson = shaDetails["files"]
                for filenameObj in filesjson:
                    filename = filenameObj["filename"]
                    _, ext = os.path.splitext(filename)
                    if ext.lower() not in source_ext:
                        continue
                    if filename not in dictfiles:
                        dictfiles[filename] = []
                    dictfiles[filename].append({"author": author, "date": date})
                    print(filename)
            ipage += 1
    except:
        print("Error receiving data")
        exit(0)


# GitHub repo
repo = "scottyab/rootbeer"
print(f"trying repo: {repo}")

# tokens
lstTokens = []

dictfiles = dict()
source_ext = [".kt", ".java", ".cpp", ".h", ".c", ".md", ".kts"]
countfiles(dictfiles, lstTokens, repo, source_ext)
print("Total number of files: " + str(len(dictfiles)))

file = repo.split("/")[1] + "COMMITMORE"
# change this to the path of your file
fileOutput = "data/file_" + file + ".csv"
rows = ["Filename", "Author", "Date"]
fileCSV = open(fileOutput, "w")
writer = csv.writer(fileCSV)
writer.writerow(rows)

bigcount = None
bigfilename = None
for filename, commitData in dictfiles.items():
    for data in commitData:
        rows = [filename, data["author"], data["date"]]
        writer.writerow(rows)
fileCSV.close()
print(f"saved file to {fileOutput}")
